# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ricson/hw/15618_project/project_5/project_5.cache/wt [current_project]
set_property parent.project_path /home/ricson/hw/15618_project/project_5/project_5.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/ricson/hw/15618_project/project_5/project_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property loop_count 10000 [current_fileset]
add_files -quiet /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib -sv {
  /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/new/project_5.sv
  /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/new/cifar_data.sv
  /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/new/parameters.sv
}
read_verilog -library xil_defaultlib /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/ricson/hw/15618_project/project_5/project_5.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ricson/hw/15618_project/project_5/project_5.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files /home/ricson/hw/15618_project/project_5/project_5.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7z020clg484-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
